"""add inventory and ledger tables

Revision ID: 3b76f054ba0e
Revises: fe56fa70289e
Create Date: 2026-08-27 15:25:11.921921

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = '3b76f054ba0e'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventoryitem',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('category', sa.Enum('GREEN_COFFEE', 'ROASTED_COFFEE', 'PACKAGING', 'SUPPLIES', 'OTHER', name='inventorycategory'), nullable=False),
    sa.Column('unit', sa.Enum('LBS', 'KG', 'BAGS', 'UNITS', name='inventoryunit'), nullable=False),
    sa.Column('current_qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('reorder_threshold', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('supplier', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('last_updated_ms', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventoryitem_name'), 'inventoryitem', ['name'], unique=False)
    op.create_table('ledgerentry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inventory_item_id', sa.Uuid(), nullable=False),
    sa.Column('item_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('change_type', sa.Enum('ADDITION', 'SUBTRACTION', 'ADJUSTMENT', name='ledgerchangetype'), nullable=False),
    sa.Column('quantity_change', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('resulting_qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at_ms', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventoryitem.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: autogenerate also proposed dropping 'test_table' - that table is
    # pre-existing, unrelated to this app's models, and must not be touched.
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ledgerentry')
    op.drop_index(op.f('ix_inventoryitem_name'), table_name='inventoryitem')
    op.drop_table('inventoryitem')
    # ### end Alembic commands ###
